@extends('admins.layouts.app')

@section('content')

<link rel="stylesheet" href="{{asset('public/admin_assets/plugins/dataTables/jquery.dataTables.min.css')}}">

<style type="text/css">
  .col-sm-12.opportunity {
    margin-top: 15px;
    position: sticky;
}
input#followUpProposalShared {
    zoom: 1.5;
    vertical-align: middle;
    margin-top: -1px;
}
input#followUpLeadIsPositive {
    zoom: 1.5;
    vertical-align: middle;
    margin-top: -1px;
}
input#followUpContactedDirector {
    zoom: 1.5;
    vertical-align: middle;
    margin-top: -1px;
}
input#followUpProfileShared{
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
label.followUpLabel {
    margin-bottom: 10px;
}
select.col-sm-4.followUpContactPersonName {
    height: 34px;
    width: 31%;
}
select.col-sm-4.followUpContactNumber {
    height: 34px;
    width: 31%;
    margin-left: 15px;
}
select.col-sm-4.followUpActionOption {
    height: 34px;
    width: 31%;
    margin-left: 15px;
}
label.followUpDateLabel {
    margin-left: 33px;
}
select.col-sm-6.followUpMainRemark {
    width: 48%;
    height: 34px;
}
select.col-sm-6.followUpSubjectType {
    width: 48%;
    height: 34px;
}
select.col-sm-6.followUpSubRemark {
    width: 48%;
    height: 34px;
    margin-left: 5px;
}
label.followUpMainRemark {
    margin-left: 32px;
}
textarea.col-sm-9.followUpDescription {
    width: 96.5%;
}
input#followUpManageContact {
    float: right;
    margin-right: 39px;
    height: 34px;
}
input#followUpNextFollowUp {
    zoom: 1.5;
    vertical-align: middle;
    margin-top: -1px;
}
input#followUpNextFollowUpDate {
    height: 34px;
    margin-left: 25px;
    width: 35%;
}
select#followUpDeliveryStatus {
    height: 34px;
    width: 35%;
    margin-left: 33px;
}
input[type=date]::-webkit-inner-spin-button {
    -webkit-appearance: none;
    display: none;
}
input#opsManageContact {
    height: 34px;
}
label.followUpSubject {
    margin-left: 32px;
}
label.followUpRemarks {
    margin-left: 32px;
}
input#followUpHistory {
    height: 34px;
    width: 77px;
}
span.followUpCurrentHistory {
    font-weight: normal;
}
input.autoGeneratedDate {
    margin-top: 10px;
}
input#followUpTechnicalBid {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpFinnancialBid {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpFinalResult {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpLoi {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpAgreement {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpEmdRefund {
    margin-bottom: 15px;
    height: 34px;
}
input#followUpTenderFee {
    margin-bottom: 15px;
    height: 34px;
}
.col-sm-12 {
    margin-left: 10px;
}
label.col-sm-7 {
    margin-left: -19px;
}
input#contactPersonName {
    width: 300px;
    margin-left: 37px;
    margin-bottom: 10px;
    padding-left: 10px;
    height: 34px;
}
input#contactPersonDesignation {
    width: 300px;
    padding-left: 10px;
    height: 34px;
}
input#contactPersonEmail {
    width: 300px;
    margin-left: 45px;
    padding-left: 10px;
    height: 34px;
}
input#contactPersonNumber {
    width: 300px;
    margin-bottom: 10px;
    padding-left: 10px;
    height: 34px;
}
</style>

<!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    <section class="content-header">

      <h1>

        Follow Up Form

        <!-- <small>Control panel</small> -->

      </h1>

      <ol class="breadcrumb">

        <li><a href="{{ url('employees/dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>

      </ol>

    </section>
    <section class="content">
      <div class="row">
        <div class="col-sm-12">
          <div class="box box-primary">
            <form id="followUpForm" action="{{ url('leads/follow-up') }}" method="POST" enctype="multipart/form-data">
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12 opportunity">
                      <div class="col-sm-6">
                        <label for="followUpTechnicalBid" class="col-sm-7">Date of Evaluation of Technical Bid :</label>
                        <input type="date" name="followUpTechnicalBid" id="followUpTechnicalBid" class="col-sm-5 followUpTechnicalBid" disabled>
                        <label for="followUpFinnancialBid" class="col-sm-7">Date of Evaluation of Financial Bid :</label>
                        <input type="date" name="followUpFinnancialBid" id="followUpFinnancialBid" class="col-sm-5 followUpFinnancialBid" disabled>
                        <label for="followUpFinalResult" class="col-sm-7">Date of Evaluation for final Result :</label>
                        <input type="date" name="followUpFinalResult" id="followUpFinalResult" class="col-sm-5 followUpFinalResult" disabled>
                        <label for="followUpLoi" class="col-sm-7">Date of LOI :</label>
                        <input type="date" name="followUpLoi" id="followUpLoi" class="col-sm-5 followUpLoi" disabled>
                      </div>
                      <div class="col-sm-6">
                        <label for="followUpAgreement" class="col-sm-7">Date of Agreement :</label>
                        <input type="date" name="followUpAgreement" id="followUpAgreement" class="col-sm-5 followUpAgreement" disabled>
                        <label for="followUpEmdRefund" class="col-sm-7">Date of EMD Refund :</label>
                        <input type="date" name="followUpEmdRefund" id="followUpEmdRefund" class="col-sm-5 followUpEmdRefund" disabled>
                        <label for="followUpTenderFee" class="col-sm-7">Date of Tender Fee Refund (in case of tender cancel) :</label>
                        <input type="date" name="followUpTenderFee" id="followUpTenderFee" class="col-sm-5 followUpTenderFee" disabled>
                      </div>
                      <!-- <div class="col-sm-3">
                      <label for="followUpProfileShared" class="followUpLabel"><input type="checkbox" name="followUpProfileShared" id="followUpProfileShared" class="followUpProfileShared">Profile Shared</label><br>
                      <label for="followUpProposalShared" class="followUpLabel"><input type="checkbox" name="followUpProposalShared" id="followUpProposalShared" class="followUpProposalShared">Proposal Shared</label><br>
                      <label for="followUpLeadIsPositive" class="followUpLabel"><input type="checkbox" name="followUpLeadIsPositive" id="followUpLeadIsPositive" class="followUpLeadIsPositive">Lead Is Positive</label><br>
                      <label for="followUpContactedDirector" class="followUpLabel"><input type="checkbox" name="followUpContactedDirector" id="followUpContactedDirector" class="followUpContactedDirector">Contacted Director/CEO</label>
                      </div> -->
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <input type="button" name="followUpHistory" id="followUpHistory" class="followUpHistory" value="History">
                      <label><span class="followUpCurrentHistory">Last Call : 9885494845 To Mr. Sourabh Madaan.</span></label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <label class="followUpDateLabel">FollowUp Date (Current Date)</label>
                  <div class="col-sm-12">
                      <select class="col-sm-4 followUpContactPersonName" name="followUpContactPersonName">
                          <option value="" selected disabled>Select Contact Person</option>
                          <option value="Pankaj Rawat">Pankaj Rawat</option> 
                          <option value="Sourabh Madaan">Sourabh Madaan</option>
                          <option value="Jeevan Koranga">Jeevan Koranga</option> 
                          <option value="Abhishek Gupta">Abhishek Gupta</option>    
                       </select>
                       <select class="col-sm-4 followUpContactNumber" name="followUpContactNumber">
                          <option value="" selected disabled>Show Contact Number</option>
                          <option value="8699979759">8699979759</option> 
                          <option value="8998898778">8998898778</option>
                          <option value="9867676776">9867676776</option>   
                       </select>
                       <select class="col-sm-4 followUpActionOption" name="followUpActionOption">
                          <option value="" selected disabled>Select Action Type</option>
                          <option value="SMS">SMS</option> 
                          <option value="Email Broucher">Email Broucher</option>
                          <option value="Custom Email">Custom Email</option>  
                       </select>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <label class="followUpSubject">FollowUp subject</label>
                  <div class="col-sm-12">
                      <select class="col-sm-6 followUpSubjectType" name="followUpSubjectType">
                          <option value="" selected disabled>Please Select FollowUp subject.</option>
                          <option value="Evaluation of Technical Bid">Evaluation of Technical Bid</option>
                          <option value="Evaluation of Financial Bid">Evaluation of Financial Bid</option> 
                          <option value="Evaluation for final Result">Evaluation for final Result</option>
                          <option value="LOI">LOI</option> 
                          <option value="Agreement">Agreement</option> 
                          <option value="EMD Refund">EMD Refund</option>
                          <option value="Tender Fee Refund (in case of tender cancel)">Tender Fee Refund (in case of tender cancel)</option>     
                       </select>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <label class="followUpRemarks">Remarks</label>
                  <div class="col-sm-12">
                      <select class="col-sm-6 followUpMainRemark" name="followUpMainRemark">
                          <option value="" selected disabled>Main Remarks Category</option>
                          <option value="Lead is Positive">Lead is Positive</option>  
                       </select>
                       <select class="col-sm-6 followUpSubRemark" name="followUpSubRemark">
                          <option value="" selected disabled>Sub Remarks Category</option>
                          <option value="FollowUp">FollowUp</option>   
                       </select>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                      <textarea rows="8" cols="50" class="col-sm-9 followUpDescription" name="followUpDescription" placeholder="Description"></textarea>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                      <label for="followUpNextFollowUp"><input type="Radio" name="followUpNextFollowUp" id="followUpNextFollowUp" value="One">Next FollowUp</label>
                      <input type="text" name="followUpNextFollowUpDate" class="followUpNextFollowUpDate" id="followUpNextFollowUpDate" placeholder="Please Select Date">
                      <input type="button" name="followUpManageContact" value="Manage Contact" id="followUpManageContact" class="followUpManageContact" data-toggle="modal" data-target="#addMyModal">
                  </div>
                </div>
              </div>
            </form>
            <div class="box-footer form-sidechange apply-leave-btn">
                <button type="button" class="btn btn-primary" id="createTilSubmit">Save</button>
                <a href="{{ url('employees/dashboard') }}" class="btn btn-default">Cancel</a>
              </div>
          </div>
        </div>
      </div>
    </section>
    <div class="modal fade bs-example-modal-sm" tabindex="-1" id="addMyModal">
    <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Add contact Person Details</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-12">
                <div class="col-sm-6">
                  <label>Name :</label>
                  <input type="text" id="contactPersonName" placeholder="Please enter contact person name." /><br>
                  <label>Designation :</label>
                  <input type="text" id="contactPersonDesignation" placeholder="Please enter contact person designation." />
                </div>
                <div class="col-sm-6"></div>
                <label>Mobile Number :</label>
                <input type="text" id="contactPersonNumber" placeholder="Please enter contact person mobile number." /><br>
                <label>Email Id :</label>
                <input type="text" id="contactPersonEmail" placeholder="Please enter contact person email id." />
              </div>
            </div>
          </div>
        </form>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

</div> <!-- Main content -->
  <!-- /.content-wrapper -->
<script src="{{asset('public/admin_assets/plugins/dataTables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/admin_assets/plugins/validations/jquery.validate.js')}}"></script>
<script src="{{asset('public/admin_assets/plugins/validations/additional-methods.js')}}"></script>

<script type="text/javascript">
    $( function() {
    $( "#followUpNextFollowUpDate" ).datepicker();
  } );
  </script>

@endsection