@extends('admins.layouts.app')

@section('content')

<link rel="stylesheet" href="{{asset('public/admin_assets/plugins/dataTables/jquery.dataTables.min.css')}}">

<style type="text/css">
  .col-sm-12.opportunity {
    margin-top: 15px;
    position: sticky;
  }

  .progressbar {
    counter-reset: step;
  }
  .progressbar li {
    list-style-type: none;
    width: 25%;
    float: left;
    font-size: 12px;
    position: relative;
    text-align: center;
    text-transform: capitalize;
    color: #000;
    font-weight: bold;
  }
  .progressbar li:before {
    width: 30px;
    height: 30px;
    content: counter(step);
    counter-increment: step;
    line-height: 30px;
    border: 2px solid #7d7d7d;
    display: block;
    text-align: center;
    margin: 0 auto 10px auto;
    border-radius: 50%;
    background-color: white;
  }
  .progressbar li:after {
    width: 100%;
    height: 2px;
    content: '';
    position: absolute;
    background-color: #7d7d7d;
    top: 15px;
    left: -50%;
    z-index: -1;
  }
  .progressbar li:first-child:after {
    content: none;
  }
  .progressbar li.active {
    color: green;
  }
  .progressbar li.active:before {
    border-color: #55b776;
  }
  .progressbar li.active + li:after {
    background-color: #55b776;
  }

input#proposalShared {
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
input#leadIsPositive {
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
input#contactedDirector {
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
input#profileShared{
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
label.opsLabel {
  margin-bottom: 10px;
}
select.col-sm-4.opsContactPersonName {
  height: 34px;
  width: 31%;
}
select.col-sm-4.opsContactNumber {
  height: 34px;
  width: 31%;
  margin-left: 15px;
}
select.col-sm-4.opsActionOption {
  height: 34px;
  width: 31%;
  margin-left: 15px;
}
label.followUpDateLabel {
  margin-left: 33px;
}
select.col-sm-6.opsMainRemark {
  width: 48%;
  height: 34px;
}
select.col-sm-6.opsSubRemark {
  width: 48%;
  height: 34px;
  margin-left: 5px;
}
label.opsRemarks {
  margin-left: 32px;
}
textarea.col-sm-9.opsDescription {
  width: 96.5%;
}
input#opsManageContact {
  float: right;
  margin-right: 27px;
}
input#opsNextFollowUp {
  zoom: 1.5;
  vertical-align: middle;
  margin-top: -1px;
}
input#opsNextFollowUpDate {
  height: 34px;
  margin-left: 25px;
  width: 35%;
}
select#opsDeliveryStatus {
  height: 34px;
  width: 35%;
  margin-left: 33px;
}
input[type=date]::-webkit-inner-spin-button {
  -webkit-appearance: none;
  display: none;
}
input#opsManageContact {
  height: 34px;
}
input#opsHistory {
  height: 34px;
  width: 77px;
}
span.currentHistory {
  font-weight: normal;
}
input.autoGeneratedDate {
  margin-top: 10px;
}
input#contactPersonName {
  width: 300px;
  margin-left: 37px;
  margin-bottom: 10px;
  padding-left: 10px;
  height: 34px;
}
input#contactPersonDesignation {
  width: 300px;
  padding-left: 10px;
  height: 34px;
}
input#contactPersonEmail {
  width: 300px;
  margin-left: 45px;
  padding-left: 10px;
  height: 34px;
}
input#contactPersonNumber {
  width: 300px;
  margin-bottom: 10px;
  padding-left: 10px;
  height: 34px;
}
</style>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Opportunity Progress Status
        <!-- <small>Control panel</small> -->
      </h1>
      <ol class="breadcrumb">
        <li>
          <a href="{{ url('employees/dashboard') }}">
            <i class="fa fa-dashboard"></i> Home
          </a>
        </li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-sm-12">
          <div class="box box-primary">
            <form id="opportunityProgressStatusForm" action="{{ url('leads/opportunity-progress-status') }}" method="POST" enctype="multipart/form-data">
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12 opportunity">
                    <div class="col-sm-9">
                      <ul class="progressbar">
                        <li class="active">Under FollowUp<br>
                          <input type="date" name="" class="autoGeneratedDate" disabled>
                        </li>
                        <li>Financial Proposal Shared<br>
                          <input type="date" name="" class="autoGeneratedDate" disabled>
                        </li>
                        <li>LOI<br>
                          <input type="date" name="" class="autoGeneratedDate" disabled>
                        </li>
                        <li>Aggrement<br>
                          <input type="date" name="" class="autoGeneratedDate" disabled>
                        </li>
                      </ul>
                    </div>

                    <div class="col-sm-3">
                      <label for="profileShared" class="opsLabel">
                        <input type="checkbox" name="profileShared" id="profileShared" class="profileShared">
                        Profile Shared
                      </label>
                      <br>
                      <label for="profileShared" class="opsLabel">
                        <input type="checkbox" name="proposalShared" id="proposalShared" class="proposalShared">
                        Proposal Shared
                      </label>
                      <br>
                      <label for="leadIsPositive" class="opsLabel">
                        <input type="checkbox" name="leadIsPositive" id="leadIsPositive" class="leadIsPositive">
                        Lead Is Positive
                      </label>
                      <br>
                      <label for="contactedDirector" class="opsLabel">
                        <input type="checkbox" name="contactedDirector" id="contactedDirector" class="contactedDirector">Contacted Director/CEO
                      </label>
                    </div>

                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <input type="button" name="opsHistory" id="opsHistory" class="opsHistory" value="History">
                      <label><span class="currentHistory">Last Call : 9885494845 To Mr. Sourabh Madaan.</span></label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <label class="followUpDateLabel">FollowUp Date (Current Date)</label>
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <select class="col-sm-4 opsContactPersonName" name="opsContactPersonName">
                          <option value="" selected disabled>Select Contact Person</option>
                          <option value="Pankaj Rawat">Pankaj Rawat</option> 
                          <option value="Sourabh Madaan">Sourabh Madaan</option>
                          <option value="Jeevan Koranga">Jeevan Koranga</option> 
                          <option value="Abhishek Gupta">Abhishek Gupta</option>    
                       </select>
                       <select class="col-sm-4 opsContactNumber" name="opsContactNumber">
                          <option value="" selected disabled>Show Contact Number</option>
                          <option value="8699979759">8699979759</option> 
                          <option value="8998898778">8998898778</option>
                          <option value="9867676776">9867676776</option>   
                       </select>
                       <select class="col-sm-4 opsActionOption" name="opsActionOption">
                          <option value="" selected disabled>Select Action Type</option>
                          <option value="SMS">SMS</option> 
                          <option value="Email Broucher">Email Broucher</option>
                          <option value="Custom Email">Custom Email</option>  
                       </select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <label class="opsRemarks">Remarks</label>
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <select class="col-sm-6 opsMainRemark" name="opsMainRemark">
                          <option value="" selected disabled>Main Remarks Category</option>
                          <option value="Lead is Positive">Lead is Positive</option>  
                       </select>
                       <select class="col-sm-6 opsSubRemark" name="opsSubRemark">
                          <option value="" selected disabled>Sub Remarks Category</option>
                          <option value="FollowUp">FollowUp</option>   
                       </select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <textarea rows="8" cols="50" class="col-sm-9 opsDescription" name="opsDescription" placeholder="Description"></textarea>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <label for="opsNextFollowUp"><input type="Radio" name="opsNextFollowUp" id="opsNextFollowUp" value="One">Next FollowUp</label>
                      <input type="text" name="opsNextFollowUpDate" class="opsNextFollowUpDate" id="opsNextFollowUpDate" placeholder="Please Select Date">
                      <input type="button" name="opsManageContact" value="Manage Contact" id="opsManageContact" class="opsManageContact" data-toggle="modal" data-target="#addMyModal">
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-9">
                      <label for="opsDeliveryStatus">Delivery Status :</label>
                      <select class="opsDeliveryStatus" name="opsDeliveryStatus" id="opsDeliveryStatus">
                          <option value="" selected disabled>Select Delivery Status</option>
                          <option value="Delivered">Delivered</option>
                          <option value="Pending">Pending</option>    
                       </select>
                    </div>
                  </div>
                </div>
              </div>
            </form>
            
            <div class="box-footer form-sidechange apply-leave-btn">
              <button type="button" class="btn btn-primary" id="createTilSubmit">Save</button>
              <a href="{{ url('employees/dashboard') }}" class="btn btn-default">Cancel</a>
            </div>
            
          </div>
        </div>
      </div>
    </section>

    <div class="modal fade bs-example-modal-sm" tabindex="-1" id="addMyModal">
    	<div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="mySmallModalLabel">Add contact Person Details</h4>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="col-sm-6">
                      <label>Name :</label>
                      <input type="text" id="contactPersonName" placeholder="Please enter contact person name." /><br>
                      <label>Designation :</label>
                      <input type="text" id="contactPersonDesignation" placeholder="Please enter contact person designation." />
                    </div>
                    <div class="col-sm-6"></div>
                    <label>Mobile Number :</label>
                    <input type="text" id="contactPersonNumber" placeholder="Please enter contact person mobile number." /><br>
                    <label>Email Id :</label>
                    <input type="text" id="contactPersonEmail" placeholder="Please enter contact person email id." />
                  </div>
                </div>
              </div>
            </form>
            <button type="button" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </div>
</div> <!-- Main content -->
<!-- /.content-wrapper -->
<script src="{{asset('public/admin_assets/plugins/dataTables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/admin_assets/plugins/validations/jquery.validate.js')}}"></script>
<script src="{{asset('public/admin_assets/plugins/validations/additional-methods.js')}}"></script>

 <script type="text/javascript">
    $( function() {
    $( "#opsNextFollowUpDate" ).datepicker();
  } );
  </script>
@endsection